name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / brakeman
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_bundler
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/using_bundler/Gemfile
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@922ebc4c5262cd14e07bb0e1db020984b6c064fe # v1.226.0
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: brakeman with skip install and using bundler
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          brakeman_flags: "--force"
          skip_install: 'true'
          use_bundler: 'true'
      - run: |
          test "$(bundle exec brakeman --version)" == "brakeman 5.1.2"
